server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 123456
  druid:
    # 初始化连接池 最小 最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 获取连接池等待时间
    max-wait: 60000
    # 检测间隔，关闭空闲连接
    time-between-eviction-runs-millis: 60000
    # 连接最小生存时间
    min-evictable-idle-time-millis: 300000
  redis:
    host: 127.0.0.1
    port: 6379

# 上传模式
upload:
  mode: minio
  local:
  minio:
    endpoint: http://10.86.17.141:9000
    access-key: UCXU48jZhgMCFtssilB8
    secret-key: P9UlKamMpAaWC0TpbTFyBd3Xm1I6FpzjEwEYociq
    bucket-name: test


# 配置MybatisPlus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
